### ISSUE TITLE
Version 3x.rc: module assets processing✖ ERROR undefined

### ISSUE THREAD

**Issue by muuvmuuv** [preactjs/preact-cli#984]
**Do you want to request a _feature_ or report a _bug_?**

BUG

**What is the current behaviour?**

I have had some issues with previous versions of the CLI, so I had updated to v3 but now getting new errors:

```
~/Development/CookieConsent master !2 ⇡1                                                                                                                                                                             marvinheilemann@wksphem001
❯ pnpm run docs-build

> gdpr-cookie-consent-banner@3.0.0 docs-build /Users/marvinheilemann/Development/CookieConsent
> preact build --src docs

 Build  [=================== ] 95% (4.0s) emitting
 ssr-bundle.f09e4.css ⏤  3.35 kB (+3.35 kB)
        ssr-bundle.js ⏤  40.6 kB (+40.6 kB)

ℹ INFO ⚛️ No custom sw.js detected: compiling default Service Worker.
 Build  [==================  ] 89% (1.5s) module assets processing✖ ERROR undefined
 ERROR  Command failed with exit code 1.

~/Development/CookieConsent master !2 ⇡1                                                                                                                                                                     1 8.68s marvinheilemann@wksphem001
❯ pnpm run docs-build -- --no-prerender

> gdpr-cookie-consent-banner@3.0.0 docs-build /Users/marvinheilemann/Development/CookieConsent
> preact build --src docs "--no-prerender"

ℹ INFO ⚛️ No custom sw.js detected: compiling default Service Worker.
 Build  [==================  ] 89% (2.9s) module assets processing✖ ERROR undefined
 ERROR  Command failed with exit code 1.
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. clone https://github.com/muuvmuuv/gdpr-cookie-consent-banner/tree/master
2. run `npm run docs-build`

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

```
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    pnpm: 4.9.3 - ~/.nvm/versions/node/v12.14.1/bin/pnpm <= is missing
  Browsers:
    Firefox: 72.0.2
    Safari: 13.0.5
    Edge: 80.0.361.54 <= is missing
  npmPackages:
    preact: ^10.3.2 => 10.3.2
    preact-cli: ^3.0.0-rc.9 => 3.0.0-rc.9
    preact-render-to-string: ^5.1.4 => 5.1.4
    preact-router: ^3.2.1 => 3.2.1
  npmGlobalPackages:
    preact-cli: 3.0.0-rc.9
```

**Comment by calebdelnay** [comment]
Also seeing this after upgrading from 3.0.0-rc7 to 3.0.0-rc9. Dropped back to 3.0.0-rc8 and problem was still observed. Does not happen on 3.0.0-rc7 so should be one of these commits that is the culprit https://github.com/preactjs/preact-cli/compare/3.0.0-rc.7...v3.0.0-rc.8

**Comment by prateekbh** [comment]
@developit this is possibly coming from babel-esm-plugin switching to 0.6.1 works fine
``preact build --no-esm` works fine for now

**Comment by piazz** [comment]
Same issue as @calebdelnay, fixed by reverting to rc7

**Comment by prateekbh** [comment]
@reznord is working on this

**Comment by prateekbh** [comment]
pleace check with rc.10. Also `optional chaining and `null coalescing` is not enabled as of now

**Comment by muuvmuuv** [comment]
@prateekbh

Stil not working. Tried with **npm** and **pnpm**.

```
ℹ INFO ⚛️ No custom sw.js detected: compiling default Service Worker.
 Build  [==================  ] 90% (1.6s) additional chunk assets processing

Build failed!

 ModuleBuildError: Module build failed (from ../node_modules/.pnpm/registry.npmjs.org/babel-loader/8.0.6_@babel+core@7.8.7+webpack@4.42.0/node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-modules' from '/Users/marvinheilemann/Development/CookieConsent'
    at Function.resolveSync [as sync] (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/resolve/1.15.1/node_modules/resolve/lib/sync.js:81:15)
    at resolveStandardizedName (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at /Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/config-descriptors.js:58:104
    at cachedFunction (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/gensync/1.0.0-beta.1/node_modules/gensync/index.js:244:28)
    at sync (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/gensync/1.0.0-beta.1/node_modules/gensync/index.js:84:14)
    at presets (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/Users/marvinheilemann/Development/CookieConsent/node_modules/.pnpm/registry.npmjs.org/@babel/core/7.8.7/node_modules/@babel/core/lib/config/config-chain.js:320:26)
```

When I install the missing package:

```
Build failed!

 ModuleParseError: Module parse failed: Unexpected token (61:16)
File was processed with these loaders:
 * ../node_modules/.pnpm/registry.npmjs.org/babel-loader/8.0.6_@babel+core@7.8.7+webpack@4.42.0/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     console.log(JSON.stringify(content, null, 2));
|
>     if (content?.choices) {
|       this.setChoices(content.choices);
|       this.initStartUpEvents();
```

**Comment by muuvmuuv** [comment]
Okay, seems like babel can not handle optional chaining. Can Preact use a babelrc file? I tried to add this with no success:

**.babelrc.json**:

```json
{
  "plugins": [
    "@babel/plugin-syntax-optional-chaining"
  ]
}
```

**Comment by reznord** [comment]
> Can Preact use a babelrc file?

Right now it is not supported. I am working on it and you can follow up the progress on #1052 

> seems like babel can not handle optional chaining

preset-modules doesn't support optional chaining as of now. Babel team is planning to integrate `preset-modules` in `preset-env`. There's an open PR for that here https://github.com/babel/babel/pull/11083

In the meanwhile, we can add the optional-chaining plugin to babel config and release a new RC.

@prateekbh WDYT!

**Comment by prateekbh** [comment]
@developit can comment better on this

**Comment by reznord** [comment]
This is fixed in the latest rc version.
